<a href="https://colab.research.google.com/github/keerthana-sree/Data_scienctist/blob/main/heart_disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("framingham_heart_disease.csv")
df.head()

male  age  education  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39        4.0              0         0.0     0.0                0   
1     0   46        2.0              0         0.0     0.0                0   
2     1   48        1.0              1        20.0     0.0                0   
3     0   61        3.0              1        30.0     0.0                0   
4     0   46        3.0              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [ ]:
df.isnull().sum()

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [ ]:
df = df.drop(['education'],axis =1)
df.head()

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0     1   39              0         0.0     0.0                0   
1     0   46              0         0.0     0.0                0   
2     1   48              1        20.0     0.0                0   
3     0   61              1        30.0     0.0                0   
4     0   46              1        23.0     0.0                0   

   prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  \
0             0         0    195.0  106.0   70.0  26.97       80.0     77.0   
1             0         0    250.0  121.0   81.0  28.73       95.0     76.0   
2             0         0    245.0  127.5   80.0  25.34       75.0     70.0   
3             1         0    225.0  150.0   95.0  28.58       65.0    103.0   
4             0         0    285.0  130.0   84.0  23.10       85.0     85.0   

   TenYearCHD  
0           0  
1           0  
2           0  
3           1  
4           0

In [ ]:
df['cigsPerDay'].mean()


np.float64(9.003088619624615)

In [ ]:
cig_mean=round(df['cigsPerDay'].mean())
cig_mean

9

In [ ]:
df['cigsPerDay'].fillna(cig_mean,inplace = True)

/tmp/ipython-input-2174189967.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cigsPerDay'].fillna(cig_mean,inplace = True)


In [ ]:
df['BPMeds'].mean()

np.float64(0.02962962962962963)

In [ ]:
bp_mean=round(df['BPMeds'].mean())
bp_mean

0

In [ ]:
df['BPMeds'].fillna(cig_mean,inplace=True)

/tmp/ipython-input-2394895996.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BPMeds'].fillna(cig_mean,inplace=True)


In [ ]:
df['BMI'].mean()

np.float64(0.14181217555450684)

In [ ]:
bp_mean=round(df['BMI'].mean())
bp_mean

26

In [ ]:
df['BMI'].fillna(cig_mean,inplace=True)

/tmp/ipython-input-3914281005.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BMI'].fillna(cig_mean,inplace=True)


In [ ]:
df['heartRate'].mean()

np.float64(75.87892376681614)

In [ ]:
bp_mean=round(df['heartRate'].mean())
bp_mean

76

In [ ]:
df['heartRate'].fillna(cig_mean,inplace=True)

/tmp/ipython-input-1120629542.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['heartRate'].fillna(cig_mean,inplace=True)


In [ ]:
df['glucose'].mean()

np.float64(81.96675324675324)

In [ ]:
bp_mean=round(df['glucose'].mean())
bp_mean

82

In [ ]:
df['glucose'].fillna(cig_mean,inplace=True)

/tmp/ipython-input-3667418685.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['glucose'].fillna(cig_mean,inplace=True)


In [ ]:
df['totChol'].mean()

np.float64(236.72158548233045)

In [ ]:
bp_mean=round(df['totChol'].mean())
bp_mean

237

In [ ]:
df['totChol'].fillna(cig_mean,inplace=True)

/tmp/ipython-input-3215521970.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['totChol'].fillna(cig_mean,inplace=True)


In [ ]:
df.isnull().sum()

male               0
age                0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [ ]:
x =df.drop('TenYearCHD',axis=1)
x

male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
0        1   39              0         0.0     0.0                0   
1        0   46              0         0.0     0.0                0   
2        1   48              1        20.0     0.0                0   
3        0   61              1        30.0     0.0                0   
4        0   46              1        23.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
4233     1   50              1         1.0     0.0                0   
4234     1   51              1        43.0     0.0                0   
4235     0   48              1        20.0     9.0                0   
4236     0   44              1        15.0     0.0                0   
4237     0   52              0         0.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
0                0         0    195.0  106.0   70.0  26.97       80.0     77.0  
1                0         0    250.0  121.0   81.0  28.73       95.0     76.0  
2                0         0    245.0  127.5   80.0  25.34       75.0     70.0  
3                1         0    225.0  150.0   95.0  28.58       65.0    103.0  
4                0         0    285.0  130.0   84.0  23.10       85.0     85.0  
...            ...       ...      ...    ...    ...    ...        ...      ...  
4233             1         0    313.0  179.0   92.0  25.97       66.0     86.0  
4234             0         0    207.0  126.5   80.0  19.71       65.0     68.0  
4235             0         0    248.0  131.0   72.0  22.00       84.0     86.0  
4236             0         0    210.0  126.5   87.0  19.16       86.0      9.0  
4237             0         0    269.0  133.5   83.0  21.47       80.0    107.0  

[4238 rows x 14 columns]

In [ ]:
y=df['TenYearCHD']
y

0       0
1       0
2       0
3       1
4       0
       ..
4233    1
4234    0
4235    0
4236    0
4237    0
Name: TenYearCHD, Length: 4238, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
print(train_test_split(x,y,test_size=0.25))
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25)

[      male  age  currentSmoker  cigsPerDay  BPMeds  prevalentStroke  \
1022     1   36              0         0.0     0.0                0   
1598     0   58              1         1.0     0.0                0   
1157     0   41              0         0.0     0.0                0   
1502     1   64              0         0.0     0.0                0   
653      1   57              1        10.0     0.0                0   
...    ...  ...            ...         ...     ...              ...   
1493     1   46              1        20.0     0.0                0   
3762     1   39              1        15.0     0.0                0   
551      0   55              1        20.0     0.0                0   
3714     1   53              0         0.0     0.0                0   
1569     0   41              1        20.0     0.0                0   

      prevalentHyp  diabetes  totChol  sysBP  diaBP    BMI  heartRate  glucose  
1022             1         0    167.0  155.0   74.0  19.42      1

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
from sklearn.metrics import accuracy_score
x_train_predicted = classifier.predict(x_train)
x_train_predicted

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
train_accuracy = accuracy_score(y_train,x_train_predicted)
train_accuracy

0.8461296412838263

In [ ]:
x_test_prediction = classifier.predict(x_test)
x_test_prediction

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
test_accuracy = accuracy_score(y_test,x_test_prediction)
test_accuracy

0.8433962264150944

In [ ]:
from sklearn.metrics import classification_report
cr = classification_report(y_test,x_test_prediction)
print(cr)

              precision    recall  f1-score   support

           0       0.85      0.99      0.91       898
           1       0.30      0.02      0.03       162

    accuracy                           0.84      1060
   macro avg       0.57      0.51      0.47      1060
weighted avg       0.76      0.84      0.78      1060



In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,x_test_prediction)
cm

array([[891,   7],
       [159,   3]])